/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SlaRouteImport } from './routes/sla'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EscalationsRouteImport } from './routes/escalations'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InboxIndexRouteImport } from './routes/inbox.index'
import { Route as SetupOrganisationRouteImport } from './routes/setup.organisation'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as InboxIdRouteImport } from './routes/inbox.$id'
import { Route as ConfigWorkflowRouteImport } from './routes/config.workflow'
import { Route as ConfigComplaintTypesRouteImport } from './routes/config.complaint-types'
import { Route as ComplaintsNewRouteImport } from './routes/complaints.new'
import { Route as AuthGoogleRouteImport } from './routes/auth.google'
import { Route as AdminWorkflowConfigRouteImport } from './routes/admin.workflow-config'
import { Route as AdminValidationRulesRouteImport } from './routes/admin.validation-rules'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminUserStatsRouteImport } from './routes/admin.user-stats'
import { Route as AdminTelemetryRouteImport } from './routes/admin.telemetry'
import { Route as AdminSourcesRouteImport } from './routes/admin.sources'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminPlatformHealthRouteImport } from './routes/admin.platform-health'
import { Route as AdminPlatformAdministratorsRouteImport } from './routes/admin.platform-administrators'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminMonitoringRouteImport } from './routes/admin.monitoring'
import { Route as AdminMasterDataSchemasRouteImport } from './routes/admin.master-data-schemas'
import { Route as AdminLocalizationRouteImport } from './routes/admin.localization'
import { Route as AdminKnowledgeBaseRouteImport } from './routes/admin.knowledge-base'
import { Route as AdminIntegrationsRouteImport } from './routes/admin.integrations'
import { Route as AdminInstallationRouteImport } from './routes/admin.installation'
import { Route as AdminHomeRouteImport } from './routes/admin.home'
import { Route as AdminHelpRouteImport } from './routes/admin.help'
import { Route as AdminGeographiesRouteImport } from './routes/admin.geographies'
import { Route as AdminDomainsRouteImport } from './routes/admin.domains'
import { Route as AdminDocumentationRouteImport } from './routes/admin.documentation'
import { Route as AdminDashboardsRouteImport } from './routes/admin.dashboards'
import { Route as AdminConfigurationRegistryRouteImport } from './routes/admin.configuration-registry'
import { Route as AdminComplaintsConfigRouteImport } from './routes/admin.complaints-config'
import { Route as AdminCommunicationsRouteImport } from './routes/admin.communications'
import { Route as AdminChannelsRouteImport } from './routes/admin.channels'
import { Route as AdminAuthenticationRouteImport } from './routes/admin.authentication'
import { Route as AdminAuditLogRouteImport } from './routes/admin.audit-log'
import { Route as AdminAccountsRouteImport } from './routes/admin.accounts'
import { Route as OrgLoginRouteImport } from './routes/$org.login'
import { Route as AdminWorkflowConfigIndexRouteImport } from './routes/admin.workflow-config.index'
import { Route as AdminDataDictionaryIndexRouteImport } from './routes/admin.data-dictionary.index'
import { Route as AdminDashboardsIndexRouteImport } from './routes/admin.dashboards.index'
import { Route as AdminWorkflowConfigVisualizationRouteImport } from './routes/admin.workflow-config.visualization'
import { Route as AdminWorkflowConfigSlaMapsRouteImport } from './routes/admin.workflow-config.sla-maps'
import { Route as AdminWorkflowConfigRoleHierarchyRouteImport } from './routes/admin.workflow-config.role-hierarchy'
import { Route as AdminTemplatesWorkflowsRouteImport } from './routes/admin.templates.workflows'
import { Route as AdminTemplatesUseCasesRouteImport } from './routes/admin.templates.use-cases'
import { Route as AdminTemplatesRolesRouteImport } from './routes/admin.templates.roles'
import { Route as AdminTemplatesKpisRouteImport } from './routes/admin.templates.kpis'
import { Route as AdminTemplatesFormsRouteImport } from './routes/admin.templates.forms'
import { Route as AdminDataDictionaryKpiIdRouteImport } from './routes/admin.data-dictionary.$kpiId'
import { Route as AdminDashboardsDashboardIdRouteImport } from './routes/admin.dashboards.$dashboardId'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SlaRoute = SlaRouteImport.update({
  id: '/sla',
  path: '/sla',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EscalationsRoute = EscalationsRouteImport.update({
  id: '/escalations',
  path: '/escalations',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxIndexRoute = InboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupOrganisationRoute = SetupOrganisationRouteImport.update({
  id: '/setup/organisation',
  path: '/setup/organisation',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxIdRoute = InboxIdRouteImport.update({
  id: '/inbox/$id',
  path: '/inbox/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigWorkflowRoute = ConfigWorkflowRouteImport.update({
  id: '/config/workflow',
  path: '/config/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigComplaintTypesRoute = ConfigComplaintTypesRouteImport.update({
  id: '/config/complaint-types',
  path: '/config/complaint-types',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsNewRoute = ComplaintsNewRouteImport.update({
  id: '/complaints/new',
  path: '/complaints/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleRoute = AuthGoogleRouteImport.update({
  id: '/auth/google',
  path: '/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorkflowConfigRoute = AdminWorkflowConfigRouteImport.update({
  id: '/workflow-config',
  path: '/workflow-config',
  getParentRoute: () => AdminRoute,
} as any)
const AdminValidationRulesRoute = AdminValidationRulesRouteImport.update({
  id: '/validation-rules',
  path: '/validation-rules',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUserStatsRoute = AdminUserStatsRouteImport.update({
  id: '/user-stats',
  path: '/user-stats',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTelemetryRoute = AdminTelemetryRouteImport.update({
  id: '/telemetry',
  path: '/telemetry',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSourcesRoute = AdminSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlatformHealthRoute = AdminPlatformHealthRouteImport.update({
  id: '/platform-health',
  path: '/platform-health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlatformAdministratorsRoute =
  AdminPlatformAdministratorsRouteImport.update({
    id: '/platform-administrators',
    path: '/platform-administrators',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMonitoringRoute = AdminMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMasterDataSchemasRoute = AdminMasterDataSchemasRouteImport.update({
  id: '/master-data-schemas',
  path: '/master-data-schemas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLocalizationRoute = AdminLocalizationRouteImport.update({
  id: '/localization',
  path: '/localization',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKnowledgeBaseRoute = AdminKnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInstallationRoute = AdminInstallationRouteImport.update({
  id: '/installation',
  path: '/installation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomeRoute = AdminHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHelpRoute = AdminHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGeographiesRoute = AdminGeographiesRouteImport.update({
  id: '/geographies',
  path: '/geographies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDomainsRoute = AdminDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocumentationRoute = AdminDocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardsRoute = AdminDashboardsRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfigurationRegistryRoute =
  AdminConfigurationRegistryRouteImport.update({
    id: '/configuration-registry',
    path: '/configuration-registry',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminComplaintsConfigRoute = AdminComplaintsConfigRouteImport.update({
  id: '/complaints-config',
  path: '/complaints-config',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunicationsRoute = AdminCommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChannelsRoute = AdminChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuthenticationRoute = AdminAuthenticationRouteImport.update({
  id: '/authentication',
  path: '/authentication',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountsRoute = AdminAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AdminRoute,
} as any)
const OrgLoginRoute = OrgLoginRouteImport.update({
  id: '/$org/login',
  path: '/$org/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorkflowConfigIndexRoute =
  AdminWorkflowConfigIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminWorkflowConfigRoute,
  } as any)
const AdminDataDictionaryIndexRoute =
  AdminDataDictionaryIndexRouteImport.update({
    id: '/data-dictionary/',
    path: '/data-dictionary/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminDashboardsIndexRoute = AdminDashboardsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDashboardsRoute,
} as any)
const AdminWorkflowConfigVisualizationRoute =
  AdminWorkflowConfigVisualizationRouteImport.update({
    id: '/visualization',
    path: '/visualization',
    getParentRoute: () => AdminWorkflowConfigRoute,
  } as any)
const AdminWorkflowConfigSlaMapsRoute =
  AdminWorkflowConfigSlaMapsRouteImport.update({
    id: '/sla-maps',
    path: '/sla-maps',
    getParentRoute: () => AdminWorkflowConfigRoute,
  } as any)
const AdminWorkflowConfigRoleHierarchyRoute =
  AdminWorkflowConfigRoleHierarchyRouteImport.update({
    id: '/role-hierarchy',
    path: '/role-hierarchy',
    getParentRoute: () => AdminWorkflowConfigRoute,
  } as any)
const AdminTemplatesWorkflowsRoute = AdminTemplatesWorkflowsRouteImport.update({
  id: '/templates/workflows',
  path: '/templates/workflows',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTemplatesUseCasesRoute = AdminTemplatesUseCasesRouteImport.update({
  id: '/templates/use-cases',
  path: '/templates/use-cases',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTemplatesRolesRoute = AdminTemplatesRolesRouteImport.update({
  id: '/templates/roles',
  path: '/templates/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTemplatesKpisRoute = AdminTemplatesKpisRouteImport.update({
  id: '/templates/kpis',
  path: '/templates/kpis',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTemplatesFormsRoute = AdminTemplatesFormsRouteImport.update({
  id: '/templates/forms',
  path: '/templates/forms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDataDictionaryKpiIdRoute =
  AdminDataDictionaryKpiIdRouteImport.update({
    id: '/data-dictionary/$kpiId',
    path: '/data-dictionary/$kpiId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminDashboardsDashboardIdRoute =
  AdminDashboardsDashboardIdRouteImport.update({
    id: '/$dashboardId',
    path: '/$dashboardId',
    getParentRoute: () => AdminDashboardsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/audit': typeof AuditRoute
  '/dashboard': typeof DashboardRoute
  '/escalations': typeof EscalationsRoute
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRoute
  '/reports': typeof ReportsRoute
  '/signup': typeof SignupRoute
  '/sla': typeof SlaRoute
  '/tasks': typeof TasksRoute
  '/users': typeof UsersRoute
  '/$org/login': typeof OrgLoginRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/authentication': typeof AdminAuthenticationRoute
  '/admin/channels': typeof AdminChannelsRoute
  '/admin/communications': typeof AdminCommunicationsRoute
  '/admin/complaints-config': typeof AdminComplaintsConfigRoute
  '/admin/configuration-registry': typeof AdminConfigurationRegistryRoute
  '/admin/dashboards': typeof AdminDashboardsRouteWithChildren
  '/admin/documentation': typeof AdminDocumentationRoute
  '/admin/domains': typeof AdminDomainsRoute
  '/admin/geographies': typeof AdminGeographiesRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/installation': typeof AdminInstallationRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/knowledge-base': typeof AdminKnowledgeBaseRoute
  '/admin/localization': typeof AdminLocalizationRoute
  '/admin/master-data-schemas': typeof AdminMasterDataSchemasRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/platform-administrators': typeof AdminPlatformAdministratorsRoute
  '/admin/platform-health': typeof AdminPlatformHealthRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/telemetry': typeof AdminTelemetryRoute
  '/admin/user-stats': typeof AdminUserStatsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/validation-rules': typeof AdminValidationRulesRoute
  '/admin/workflow-config': typeof AdminWorkflowConfigRouteWithChildren
  '/auth/google': typeof AuthGoogleRoute
  '/complaints/new': typeof ComplaintsNewRoute
  '/config/complaint-types': typeof ConfigComplaintTypesRoute
  '/config/workflow': typeof ConfigWorkflowRoute
  '/inbox/$id': typeof InboxIdRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/setup/organisation': typeof SetupOrganisationRoute
  '/inbox/': typeof InboxIndexRoute
  '/admin/dashboards/$dashboardId': typeof AdminDashboardsDashboardIdRoute
  '/admin/data-dictionary/$kpiId': typeof AdminDataDictionaryKpiIdRoute
  '/admin/templates/forms': typeof AdminTemplatesFormsRoute
  '/admin/templates/kpis': typeof AdminTemplatesKpisRoute
  '/admin/templates/roles': typeof AdminTemplatesRolesRoute
  '/admin/templates/use-cases': typeof AdminTemplatesUseCasesRoute
  '/admin/templates/workflows': typeof AdminTemplatesWorkflowsRoute
  '/admin/workflow-config/role-hierarchy': typeof AdminWorkflowConfigRoleHierarchyRoute
  '/admin/workflow-config/sla-maps': typeof AdminWorkflowConfigSlaMapsRoute
  '/admin/workflow-config/visualization': typeof AdminWorkflowConfigVisualizationRoute
  '/admin/dashboards/': typeof AdminDashboardsIndexRoute
  '/admin/data-dictionary/': typeof AdminDataDictionaryIndexRoute
  '/admin/workflow-config/': typeof AdminWorkflowConfigIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/audit': typeof AuditRoute
  '/dashboard': typeof DashboardRoute
  '/escalations': typeof EscalationsRoute
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRoute
  '/reports': typeof ReportsRoute
  '/signup': typeof SignupRoute
  '/sla': typeof SlaRoute
  '/tasks': typeof TasksRoute
  '/users': typeof UsersRoute
  '/$org/login': typeof OrgLoginRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/authentication': typeof AdminAuthenticationRoute
  '/admin/channels': typeof AdminChannelsRoute
  '/admin/communications': typeof AdminCommunicationsRoute
  '/admin/complaints-config': typeof AdminComplaintsConfigRoute
  '/admin/configuration-registry': typeof AdminConfigurationRegistryRoute
  '/admin/documentation': typeof AdminDocumentationRoute
  '/admin/domains': typeof AdminDomainsRoute
  '/admin/geographies': typeof AdminGeographiesRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/installation': typeof AdminInstallationRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/knowledge-base': typeof AdminKnowledgeBaseRoute
  '/admin/localization': typeof AdminLocalizationRoute
  '/admin/master-data-schemas': typeof AdminMasterDataSchemasRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/platform-administrators': typeof AdminPlatformAdministratorsRoute
  '/admin/platform-health': typeof AdminPlatformHealthRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/telemetry': typeof AdminTelemetryRoute
  '/admin/user-stats': typeof AdminUserStatsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/validation-rules': typeof AdminValidationRulesRoute
  '/auth/google': typeof AuthGoogleRoute
  '/complaints/new': typeof ComplaintsNewRoute
  '/config/complaint-types': typeof ConfigComplaintTypesRoute
  '/config/workflow': typeof ConfigWorkflowRoute
  '/inbox/$id': typeof InboxIdRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/setup/organisation': typeof SetupOrganisationRoute
  '/inbox': typeof InboxIndexRoute
  '/admin/dashboards/$dashboardId': typeof AdminDashboardsDashboardIdRoute
  '/admin/data-dictionary/$kpiId': typeof AdminDataDictionaryKpiIdRoute
  '/admin/templates/forms': typeof AdminTemplatesFormsRoute
  '/admin/templates/kpis': typeof AdminTemplatesKpisRoute
  '/admin/templates/roles': typeof AdminTemplatesRolesRoute
  '/admin/templates/use-cases': typeof AdminTemplatesUseCasesRoute
  '/admin/templates/workflows': typeof AdminTemplatesWorkflowsRoute
  '/admin/workflow-config/role-hierarchy': typeof AdminWorkflowConfigRoleHierarchyRoute
  '/admin/workflow-config/sla-maps': typeof AdminWorkflowConfigSlaMapsRoute
  '/admin/workflow-config/visualization': typeof AdminWorkflowConfigVisualizationRoute
  '/admin/dashboards': typeof AdminDashboardsIndexRoute
  '/admin/data-dictionary': typeof AdminDataDictionaryIndexRoute
  '/admin/workflow-config': typeof AdminWorkflowConfigIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/audit': typeof AuditRoute
  '/dashboard': typeof DashboardRoute
  '/escalations': typeof EscalationsRoute
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRoute
  '/reports': typeof ReportsRoute
  '/signup': typeof SignupRoute
  '/sla': typeof SlaRoute
  '/tasks': typeof TasksRoute
  '/users': typeof UsersRoute
  '/$org/login': typeof OrgLoginRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/authentication': typeof AdminAuthenticationRoute
  '/admin/channels': typeof AdminChannelsRoute
  '/admin/communications': typeof AdminCommunicationsRoute
  '/admin/complaints-config': typeof AdminComplaintsConfigRoute
  '/admin/configuration-registry': typeof AdminConfigurationRegistryRoute
  '/admin/dashboards': typeof AdminDashboardsRouteWithChildren
  '/admin/documentation': typeof AdminDocumentationRoute
  '/admin/domains': typeof AdminDomainsRoute
  '/admin/geographies': typeof AdminGeographiesRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/installation': typeof AdminInstallationRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/knowledge-base': typeof AdminKnowledgeBaseRoute
  '/admin/localization': typeof AdminLocalizationRoute
  '/admin/master-data-schemas': typeof AdminMasterDataSchemasRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/platform-administrators': typeof AdminPlatformAdministratorsRoute
  '/admin/platform-health': typeof AdminPlatformHealthRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/telemetry': typeof AdminTelemetryRoute
  '/admin/user-stats': typeof AdminUserStatsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/validation-rules': typeof AdminValidationRulesRoute
  '/admin/workflow-config': typeof AdminWorkflowConfigRouteWithChildren
  '/auth/google': typeof AuthGoogleRoute
  '/complaints/new': typeof ComplaintsNewRoute
  '/config/complaint-types': typeof ConfigComplaintTypesRoute
  '/config/workflow': typeof ConfigWorkflowRoute
  '/inbox/$id': typeof InboxIdRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/setup/organisation': typeof SetupOrganisationRoute
  '/inbox/': typeof InboxIndexRoute
  '/admin/dashboards/$dashboardId': typeof AdminDashboardsDashboardIdRoute
  '/admin/data-dictionary/$kpiId': typeof AdminDataDictionaryKpiIdRoute
  '/admin/templates/forms': typeof AdminTemplatesFormsRoute
  '/admin/templates/kpis': typeof AdminTemplatesKpisRoute
  '/admin/templates/roles': typeof AdminTemplatesRolesRoute
  '/admin/templates/use-cases': typeof AdminTemplatesUseCasesRoute
  '/admin/templates/workflows': typeof AdminTemplatesWorkflowsRoute
  '/admin/workflow-config/role-hierarchy': typeof AdminWorkflowConfigRoleHierarchyRoute
  '/admin/workflow-config/sla-maps': typeof AdminWorkflowConfigSlaMapsRoute
  '/admin/workflow-config/visualization': typeof AdminWorkflowConfigVisualizationRoute
  '/admin/dashboards/': typeof AdminDashboardsIndexRoute
  '/admin/data-dictionary/': typeof AdminDataDictionaryIndexRoute
  '/admin/workflow-config/': typeof AdminWorkflowConfigIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/audit'
    | '/dashboard'
    | '/escalations'
    | '/login'
    | '/platform'
    | '/reports'
    | '/signup'
    | '/sla'
    | '/tasks'
    | '/users'
    | '/$org/login'
    | '/admin/accounts'
    | '/admin/audit-log'
    | '/admin/authentication'
    | '/admin/channels'
    | '/admin/communications'
    | '/admin/complaints-config'
    | '/admin/configuration-registry'
    | '/admin/dashboards'
    | '/admin/documentation'
    | '/admin/domains'
    | '/admin/geographies'
    | '/admin/help'
    | '/admin/home'
    | '/admin/installation'
    | '/admin/integrations'
    | '/admin/knowledge-base'
    | '/admin/localization'
    | '/admin/master-data-schemas'
    | '/admin/monitoring'
    | '/admin/notifications'
    | '/admin/platform-administrators'
    | '/admin/platform-health'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/sources'
    | '/admin/telemetry'
    | '/admin/user-stats'
    | '/admin/users'
    | '/admin/validation-rules'
    | '/admin/workflow-config'
    | '/auth/google'
    | '/complaints/new'
    | '/config/complaint-types'
    | '/config/workflow'
    | '/inbox/$id'
    | '/legal/privacy'
    | '/legal/terms'
    | '/setup/organisation'
    | '/inbox/'
    | '/admin/dashboards/$dashboardId'
    | '/admin/data-dictionary/$kpiId'
    | '/admin/templates/forms'
    | '/admin/templates/kpis'
    | '/admin/templates/roles'
    | '/admin/templates/use-cases'
    | '/admin/templates/workflows'
    | '/admin/workflow-config/role-hierarchy'
    | '/admin/workflow-config/sla-maps'
    | '/admin/workflow-config/visualization'
    | '/admin/dashboards/'
    | '/admin/data-dictionary/'
    | '/admin/workflow-config/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/audit'
    | '/dashboard'
    | '/escalations'
    | '/login'
    | '/platform'
    | '/reports'
    | '/signup'
    | '/sla'
    | '/tasks'
    | '/users'
    | '/$org/login'
    | '/admin/accounts'
    | '/admin/audit-log'
    | '/admin/authentication'
    | '/admin/channels'
    | '/admin/communications'
    | '/admin/complaints-config'
    | '/admin/configuration-registry'
    | '/admin/documentation'
    | '/admin/domains'
    | '/admin/geographies'
    | '/admin/help'
    | '/admin/home'
    | '/admin/installation'
    | '/admin/integrations'
    | '/admin/knowledge-base'
    | '/admin/localization'
    | '/admin/master-data-schemas'
    | '/admin/monitoring'
    | '/admin/notifications'
    | '/admin/platform-administrators'
    | '/admin/platform-health'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/sources'
    | '/admin/telemetry'
    | '/admin/user-stats'
    | '/admin/users'
    | '/admin/validation-rules'
    | '/auth/google'
    | '/complaints/new'
    | '/config/complaint-types'
    | '/config/workflow'
    | '/inbox/$id'
    | '/legal/privacy'
    | '/legal/terms'
    | '/setup/organisation'
    | '/inbox'
    | '/admin/dashboards/$dashboardId'
    | '/admin/data-dictionary/$kpiId'
    | '/admin/templates/forms'
    | '/admin/templates/kpis'
    | '/admin/templates/roles'
    | '/admin/templates/use-cases'
    | '/admin/templates/workflows'
    | '/admin/workflow-config/role-hierarchy'
    | '/admin/workflow-config/sla-maps'
    | '/admin/workflow-config/visualization'
    | '/admin/dashboards'
    | '/admin/data-dictionary'
    | '/admin/workflow-config'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/audit'
    | '/dashboard'
    | '/escalations'
    | '/login'
    | '/platform'
    | '/reports'
    | '/signup'
    | '/sla'
    | '/tasks'
    | '/users'
    | '/$org/login'
    | '/admin/accounts'
    | '/admin/audit-log'
    | '/admin/authentication'
    | '/admin/channels'
    | '/admin/communications'
    | '/admin/complaints-config'
    | '/admin/configuration-registry'
    | '/admin/dashboards'
    | '/admin/documentation'
    | '/admin/domains'
    | '/admin/geographies'
    | '/admin/help'
    | '/admin/home'
    | '/admin/installation'
    | '/admin/integrations'
    | '/admin/knowledge-base'
    | '/admin/localization'
    | '/admin/master-data-schemas'
    | '/admin/monitoring'
    | '/admin/notifications'
    | '/admin/platform-administrators'
    | '/admin/platform-health'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/sources'
    | '/admin/telemetry'
    | '/admin/user-stats'
    | '/admin/users'
    | '/admin/validation-rules'
    | '/admin/workflow-config'
    | '/auth/google'
    | '/complaints/new'
    | '/config/complaint-types'
    | '/config/workflow'
    | '/inbox/$id'
    | '/legal/privacy'
    | '/legal/terms'
    | '/setup/organisation'
    | '/inbox/'
    | '/admin/dashboards/$dashboardId'
    | '/admin/data-dictionary/$kpiId'
    | '/admin/templates/forms'
    | '/admin/templates/kpis'
    | '/admin/templates/roles'
    | '/admin/templates/use-cases'
    | '/admin/templates/workflows'
    | '/admin/workflow-config/role-hierarchy'
    | '/admin/workflow-config/sla-maps'
    | '/admin/workflow-config/visualization'
    | '/admin/dashboards/'
    | '/admin/data-dictionary/'
    | '/admin/workflow-config/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuditRoute: typeof AuditRoute
  DashboardRoute: typeof DashboardRoute
  EscalationsRoute: typeof EscalationsRoute
  LoginRoute: typeof LoginRoute
  PlatformRoute: typeof PlatformRoute
  ReportsRoute: typeof ReportsRoute
  SignupRoute: typeof SignupRoute
  SlaRoute: typeof SlaRoute
  TasksRoute: typeof TasksRoute
  UsersRoute: typeof UsersRoute
  OrgLoginRoute: typeof OrgLoginRoute
  AuthGoogleRoute: typeof AuthGoogleRoute
  ComplaintsNewRoute: typeof ComplaintsNewRoute
  ConfigComplaintTypesRoute: typeof ConfigComplaintTypesRoute
  ConfigWorkflowRoute: typeof ConfigWorkflowRoute
  InboxIdRoute: typeof InboxIdRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  SetupOrganisationRoute: typeof SetupOrganisationRoute
  InboxIndexRoute: typeof InboxIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sla': {
      id: '/sla'
      path: '/sla'
      fullPath: '/sla'
      preLoaderRoute: typeof SlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escalations': {
      id: '/escalations'
      path: '/escalations'
      fullPath: '/escalations'
      preLoaderRoute: typeof EscalationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/': {
      id: '/inbox/'
      path: '/inbox'
      fullPath: '/inbox/'
      preLoaderRoute: typeof InboxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/organisation': {
      id: '/setup/organisation'
      path: '/setup/organisation'
      fullPath: '/setup/organisation'
      preLoaderRoute: typeof SetupOrganisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/$id': {
      id: '/inbox/$id'
      path: '/inbox/$id'
      fullPath: '/inbox/$id'
      preLoaderRoute: typeof InboxIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/workflow': {
      id: '/config/workflow'
      path: '/config/workflow'
      fullPath: '/config/workflow'
      preLoaderRoute: typeof ConfigWorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/complaint-types': {
      id: '/config/complaint-types'
      path: '/config/complaint-types'
      fullPath: '/config/complaint-types'
      preLoaderRoute: typeof ConfigComplaintTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints/new': {
      id: '/complaints/new'
      path: '/complaints/new'
      fullPath: '/complaints/new'
      preLoaderRoute: typeof ComplaintsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google': {
      id: '/auth/google'
      path: '/auth/google'
      fullPath: '/auth/google'
      preLoaderRoute: typeof AuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/workflow-config': {
      id: '/admin/workflow-config'
      path: '/workflow-config'
      fullPath: '/admin/workflow-config'
      preLoaderRoute: typeof AdminWorkflowConfigRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/validation-rules': {
      id: '/admin/validation-rules'
      path: '/validation-rules'
      fullPath: '/admin/validation-rules'
      preLoaderRoute: typeof AdminValidationRulesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/user-stats': {
      id: '/admin/user-stats'
      path: '/user-stats'
      fullPath: '/admin/user-stats'
      preLoaderRoute: typeof AdminUserStatsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/telemetry': {
      id: '/admin/telemetry'
      path: '/telemetry'
      fullPath: '/admin/telemetry'
      preLoaderRoute: typeof AdminTelemetryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sources': {
      id: '/admin/sources'
      path: '/sources'
      fullPath: '/admin/sources'
      preLoaderRoute: typeof AdminSourcesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/platform-health': {
      id: '/admin/platform-health'
      path: '/platform-health'
      fullPath: '/admin/platform-health'
      preLoaderRoute: typeof AdminPlatformHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/platform-administrators': {
      id: '/admin/platform-administrators'
      path: '/platform-administrators'
      fullPath: '/admin/platform-administrators'
      preLoaderRoute: typeof AdminPlatformAdministratorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/monitoring': {
      id: '/admin/monitoring'
      path: '/monitoring'
      fullPath: '/admin/monitoring'
      preLoaderRoute: typeof AdminMonitoringRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/master-data-schemas': {
      id: '/admin/master-data-schemas'
      path: '/master-data-schemas'
      fullPath: '/admin/master-data-schemas'
      preLoaderRoute: typeof AdminMasterDataSchemasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/localization': {
      id: '/admin/localization'
      path: '/localization'
      fullPath: '/admin/localization'
      preLoaderRoute: typeof AdminLocalizationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/knowledge-base': {
      id: '/admin/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/admin/knowledge-base'
      preLoaderRoute: typeof AdminKnowledgeBaseRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/installation': {
      id: '/admin/installation'
      path: '/installation'
      fullPath: '/admin/installation'
      preLoaderRoute: typeof AdminInstallationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/home': {
      id: '/admin/home'
      path: '/home'
      fullPath: '/admin/home'
      preLoaderRoute: typeof AdminHomeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/help': {
      id: '/admin/help'
      path: '/help'
      fullPath: '/admin/help'
      preLoaderRoute: typeof AdminHelpRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/geographies': {
      id: '/admin/geographies'
      path: '/geographies'
      fullPath: '/admin/geographies'
      preLoaderRoute: typeof AdminGeographiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/domains': {
      id: '/admin/domains'
      path: '/domains'
      fullPath: '/admin/domains'
      preLoaderRoute: typeof AdminDomainsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/documentation': {
      id: '/admin/documentation'
      path: '/documentation'
      fullPath: '/admin/documentation'
      preLoaderRoute: typeof AdminDocumentationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboards': {
      id: '/admin/dashboards'
      path: '/dashboards'
      fullPath: '/admin/dashboards'
      preLoaderRoute: typeof AdminDashboardsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuration-registry': {
      id: '/admin/configuration-registry'
      path: '/configuration-registry'
      fullPath: '/admin/configuration-registry'
      preLoaderRoute: typeof AdminConfigurationRegistryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/complaints-config': {
      id: '/admin/complaints-config'
      path: '/complaints-config'
      fullPath: '/admin/complaints-config'
      preLoaderRoute: typeof AdminComplaintsConfigRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/communications': {
      id: '/admin/communications'
      path: '/communications'
      fullPath: '/admin/communications'
      preLoaderRoute: typeof AdminCommunicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/channels': {
      id: '/admin/channels'
      path: '/channels'
      fullPath: '/admin/channels'
      preLoaderRoute: typeof AdminChannelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/authentication': {
      id: '/admin/authentication'
      path: '/authentication'
      fullPath: '/admin/authentication'
      preLoaderRoute: typeof AdminAuthenticationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-log': {
      id: '/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/accounts': {
      id: '/admin/accounts'
      path: '/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AdminAccountsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$org/login': {
      id: '/$org/login'
      path: '/$org/login'
      fullPath: '/$org/login'
      preLoaderRoute: typeof OrgLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/workflow-config/': {
      id: '/admin/workflow-config/'
      path: '/'
      fullPath: '/admin/workflow-config/'
      preLoaderRoute: typeof AdminWorkflowConfigIndexRouteImport
      parentRoute: typeof AdminWorkflowConfigRoute
    }
    '/admin/data-dictionary/': {
      id: '/admin/data-dictionary/'
      path: '/data-dictionary'
      fullPath: '/admin/data-dictionary/'
      preLoaderRoute: typeof AdminDataDictionaryIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboards/': {
      id: '/admin/dashboards/'
      path: '/'
      fullPath: '/admin/dashboards/'
      preLoaderRoute: typeof AdminDashboardsIndexRouteImport
      parentRoute: typeof AdminDashboardsRoute
    }
    '/admin/workflow-config/visualization': {
      id: '/admin/workflow-config/visualization'
      path: '/visualization'
      fullPath: '/admin/workflow-config/visualization'
      preLoaderRoute: typeof AdminWorkflowConfigVisualizationRouteImport
      parentRoute: typeof AdminWorkflowConfigRoute
    }
    '/admin/workflow-config/sla-maps': {
      id: '/admin/workflow-config/sla-maps'
      path: '/sla-maps'
      fullPath: '/admin/workflow-config/sla-maps'
      preLoaderRoute: typeof AdminWorkflowConfigSlaMapsRouteImport
      parentRoute: typeof AdminWorkflowConfigRoute
    }
    '/admin/workflow-config/role-hierarchy': {
      id: '/admin/workflow-config/role-hierarchy'
      path: '/role-hierarchy'
      fullPath: '/admin/workflow-config/role-hierarchy'
      preLoaderRoute: typeof AdminWorkflowConfigRoleHierarchyRouteImport
      parentRoute: typeof AdminWorkflowConfigRoute
    }
    '/admin/templates/workflows': {
      id: '/admin/templates/workflows'
      path: '/templates/workflows'
      fullPath: '/admin/templates/workflows'
      preLoaderRoute: typeof AdminTemplatesWorkflowsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/templates/use-cases': {
      id: '/admin/templates/use-cases'
      path: '/templates/use-cases'
      fullPath: '/admin/templates/use-cases'
      preLoaderRoute: typeof AdminTemplatesUseCasesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/templates/roles': {
      id: '/admin/templates/roles'
      path: '/templates/roles'
      fullPath: '/admin/templates/roles'
      preLoaderRoute: typeof AdminTemplatesRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/templates/kpis': {
      id: '/admin/templates/kpis'
      path: '/templates/kpis'
      fullPath: '/admin/templates/kpis'
      preLoaderRoute: typeof AdminTemplatesKpisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/templates/forms': {
      id: '/admin/templates/forms'
      path: '/templates/forms'
      fullPath: '/admin/templates/forms'
      preLoaderRoute: typeof AdminTemplatesFormsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/data-dictionary/$kpiId': {
      id: '/admin/data-dictionary/$kpiId'
      path: '/data-dictionary/$kpiId'
      fullPath: '/admin/data-dictionary/$kpiId'
      preLoaderRoute: typeof AdminDataDictionaryKpiIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboards/$dashboardId': {
      id: '/admin/dashboards/$dashboardId'
      path: '/$dashboardId'
      fullPath: '/admin/dashboards/$dashboardId'
      preLoaderRoute: typeof AdminDashboardsDashboardIdRouteImport
      parentRoute: typeof AdminDashboardsRoute
    }
  }
}

interface AdminDashboardsRouteChildren {
  AdminDashboardsDashboardIdRoute: typeof AdminDashboardsDashboardIdRoute
  AdminDashboardsIndexRoute: typeof AdminDashboardsIndexRoute
}

const AdminDashboardsRouteChildren: AdminDashboardsRouteChildren = {
  AdminDashboardsDashboardIdRoute: AdminDashboardsDashboardIdRoute,
  AdminDashboardsIndexRoute: AdminDashboardsIndexRoute,
}

const AdminDashboardsRouteWithChildren = AdminDashboardsRoute._addFileChildren(
  AdminDashboardsRouteChildren,
)

interface AdminWorkflowConfigRouteChildren {
  AdminWorkflowConfigRoleHierarchyRoute: typeof AdminWorkflowConfigRoleHierarchyRoute
  AdminWorkflowConfigSlaMapsRoute: typeof AdminWorkflowConfigSlaMapsRoute
  AdminWorkflowConfigVisualizationRoute: typeof AdminWorkflowConfigVisualizationRoute
  AdminWorkflowConfigIndexRoute: typeof AdminWorkflowConfigIndexRoute
}

const AdminWorkflowConfigRouteChildren: AdminWorkflowConfigRouteChildren = {
  AdminWorkflowConfigRoleHierarchyRoute: AdminWorkflowConfigRoleHierarchyRoute,
  AdminWorkflowConfigSlaMapsRoute: AdminWorkflowConfigSlaMapsRoute,
  AdminWorkflowConfigVisualizationRoute: AdminWorkflowConfigVisualizationRoute,
  AdminWorkflowConfigIndexRoute: AdminWorkflowConfigIndexRoute,
}

const AdminWorkflowConfigRouteWithChildren =
  AdminWorkflowConfigRoute._addFileChildren(AdminWorkflowConfigRouteChildren)

interface AdminRouteChildren {
  AdminAccountsRoute: typeof AdminAccountsRoute
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminAuthenticationRoute: typeof AdminAuthenticationRoute
  AdminChannelsRoute: typeof AdminChannelsRoute
  AdminCommunicationsRoute: typeof AdminCommunicationsRoute
  AdminComplaintsConfigRoute: typeof AdminComplaintsConfigRoute
  AdminConfigurationRegistryRoute: typeof AdminConfigurationRegistryRoute
  AdminDashboardsRoute: typeof AdminDashboardsRouteWithChildren
  AdminDocumentationRoute: typeof AdminDocumentationRoute
  AdminDomainsRoute: typeof AdminDomainsRoute
  AdminGeographiesRoute: typeof AdminGeographiesRoute
  AdminHelpRoute: typeof AdminHelpRoute
  AdminHomeRoute: typeof AdminHomeRoute
  AdminInstallationRoute: typeof AdminInstallationRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminKnowledgeBaseRoute: typeof AdminKnowledgeBaseRoute
  AdminLocalizationRoute: typeof AdminLocalizationRoute
  AdminMasterDataSchemasRoute: typeof AdminMasterDataSchemasRoute
  AdminMonitoringRoute: typeof AdminMonitoringRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPlatformAdministratorsRoute: typeof AdminPlatformAdministratorsRoute
  AdminPlatformHealthRoute: typeof AdminPlatformHealthRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSourcesRoute: typeof AdminSourcesRoute
  AdminTelemetryRoute: typeof AdminTelemetryRoute
  AdminUserStatsRoute: typeof AdminUserStatsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminValidationRulesRoute: typeof AdminValidationRulesRoute
  AdminWorkflowConfigRoute: typeof AdminWorkflowConfigRouteWithChildren
  AdminDataDictionaryKpiIdRoute: typeof AdminDataDictionaryKpiIdRoute
  AdminTemplatesFormsRoute: typeof AdminTemplatesFormsRoute
  AdminTemplatesKpisRoute: typeof AdminTemplatesKpisRoute
  AdminTemplatesRolesRoute: typeof AdminTemplatesRolesRoute
  AdminTemplatesUseCasesRoute: typeof AdminTemplatesUseCasesRoute
  AdminTemplatesWorkflowsRoute: typeof AdminTemplatesWorkflowsRoute
  AdminDataDictionaryIndexRoute: typeof AdminDataDictionaryIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccountsRoute: AdminAccountsRoute,
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminAuthenticationRoute: AdminAuthenticationRoute,
  AdminChannelsRoute: AdminChannelsRoute,
  AdminCommunicationsRoute: AdminCommunicationsRoute,
  AdminComplaintsConfigRoute: AdminComplaintsConfigRoute,
  AdminConfigurationRegistryRoute: AdminConfigurationRegistryRoute,
  AdminDashboardsRoute: AdminDashboardsRouteWithChildren,
  AdminDocumentationRoute: AdminDocumentationRoute,
  AdminDomainsRoute: AdminDomainsRoute,
  AdminGeographiesRoute: AdminGeographiesRoute,
  AdminHelpRoute: AdminHelpRoute,
  AdminHomeRoute: AdminHomeRoute,
  AdminInstallationRoute: AdminInstallationRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminKnowledgeBaseRoute: AdminKnowledgeBaseRoute,
  AdminLocalizationRoute: AdminLocalizationRoute,
  AdminMasterDataSchemasRoute: AdminMasterDataSchemasRoute,
  AdminMonitoringRoute: AdminMonitoringRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPlatformAdministratorsRoute: AdminPlatformAdministratorsRoute,
  AdminPlatformHealthRoute: AdminPlatformHealthRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSourcesRoute: AdminSourcesRoute,
  AdminTelemetryRoute: AdminTelemetryRoute,
  AdminUserStatsRoute: AdminUserStatsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminValidationRulesRoute: AdminValidationRulesRoute,
  AdminWorkflowConfigRoute: AdminWorkflowConfigRouteWithChildren,
  AdminDataDictionaryKpiIdRoute: AdminDataDictionaryKpiIdRoute,
  AdminTemplatesFormsRoute: AdminTemplatesFormsRoute,
  AdminTemplatesKpisRoute: AdminTemplatesKpisRoute,
  AdminTemplatesRolesRoute: AdminTemplatesRolesRoute,
  AdminTemplatesUseCasesRoute: AdminTemplatesUseCasesRoute,
  AdminTemplatesWorkflowsRoute: AdminTemplatesWorkflowsRoute,
  AdminDataDictionaryIndexRoute: AdminDataDictionaryIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuditRoute: AuditRoute,
  DashboardRoute: DashboardRoute,
  EscalationsRoute: EscalationsRoute,
  LoginRoute: LoginRoute,
  PlatformRoute: PlatformRoute,
  ReportsRoute: ReportsRoute,
  SignupRoute: SignupRoute,
  SlaRoute: SlaRoute,
  TasksRoute: TasksRoute,
  UsersRoute: UsersRoute,
  OrgLoginRoute: OrgLoginRoute,
  AuthGoogleRoute: AuthGoogleRoute,
  ComplaintsNewRoute: ComplaintsNewRoute,
  ConfigComplaintTypesRoute: ConfigComplaintTypesRoute,
  ConfigWorkflowRoute: ConfigWorkflowRoute,
  InboxIdRoute: InboxIdRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  SetupOrganisationRoute: SetupOrganisationRoute,
  InboxIndexRoute: InboxIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
